FROM python:2.7.12
MAINTAINER Your Name "amitavasudev.kamat@sjsu.edu"
COPY . /app
WORKDIR /app
RUN pip install -r requirements.txt
ENTRYPOINT ["python", "app.py"]
CMD ["https://github.com/amitakamat/assignment1-config-example"]
